name: Generate Profile Summary Cards

on:
  workflow_dispatch:     # permite rodar manualmente
  schedule:
    - cron: "0 0 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install profile-summary-cards
        run: |
          npm install -g github-profile-summary-cards-cli

      - name: Generate cards
        run: |
          github-profile-summary-cards-cli -u NicoBernardes -t tokyonight

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update profile summary cards" || echo "No changes to commit"
          git push
